version: 2.1

#orbs:
#  maven: circleci/maven@0.0.12
#
#workflows:
#  maven_test:
#    jobs:
#      - maven/test # checkout, build, test, and upload test results

jobs: 
  build: 
    docker: 
      - image: circleci/openjdk:11.0.3-jdk-stretch
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: admin
    steps:
      - checkout
      - run: mvn -Dmaven.test.skip=true clean install
      - store_artifacts:
          path: target/classes
          destination: optivision-web-app