version: 2.1

#orbs:
#  maven: circleci/maven@0.0.12
#
#workflows:
#  maven_test:
#    jobs:
#      - maven/test # checkout, build, test, and upload test results

jobs: 
  build: 
    docker: 
      - image: circleci/openjdk:8-jdk-stretch 
    steps:
      - checkout
      - run: ./mvnw clean install 
      - store_artifacts:
          path: target/classes
          destination: optivision-web-app